### ISSUE TITLE
resolves #73 Add the Bill.com section to my Portfolio

### ISSUE THREAD

**Issue by JasonToups** [JasonToups/jasontoups.github.io#73]
Add the Bill.com section to my portfolio.

## Tasks

- [x] - get a source image
- [x] - resize the source image to match the other ones in the repo
- [x] - write the copy about working with bill
- [x] - work with ChatGPT on editing it
- [x] - create a local feature branch for this work
- [x] - create the draft pull request & link it to this ticket, so it will be moved to done when it's merged
- [x] Refactor the components to pass the data into them from the Portfolio Component
  - [x] About
  - [x] Contact
  - [x] Experience
  - [x] Header
  - [x] Projects
  - [x] Tech
